# Generated by Django 2.1.1 on 2018-09-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curatedproducts',
            name='slug',
        ),
    ]
